CATEGORIES = [
    "healthcare",
    "housing",
    "legal-rights",
    "mental-health",
    "settlement-worker",
    "community-support",
]

RESOURCES = [
    {
        "id": 1,
        "title": "Community Health Clinic",
        "description": "Walk-in care, health card guidance, and newcomer-friendly healthcare navigation.",
        "category": "healthcare",
        "imageUrl": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d",
        "location": "Toronto, ON",
        "tags": ["clinic", "walk-in", "health-card"],
        "urgent": False,
    },
    {
        "id": 2,
        "title": "Tenant Rights Help Desk",
        "description": "Support for rental questions, illegal deposits, lease issues, and housing safety.",
        "category": "housing",
        "imageUrl": "https://images.unsplash.com/photo-1560518883-ce09059eeffa",
        "location": "Vancouver, BC",
        "tags": ["tenant-rights", "renting", "legal-info"],
        "urgent": False,
    },
    {
        "id": 3,
        "title": "Legal Aid Intake Line",
        "description": "Free legal intake for eligible newcomers with housing, immigration, or safety concerns.",
        "category": "legal-rights",
        "imageUrl": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f",
        "location": "Canada-wide",
        "tags": ["legal-aid", "rights", "phone-support"],
        "urgent": True,
    },
    {
        "id": 4,
        "title": "988 Mental Health Crisis Support",
        "description": "Immediate mental health crisis support available by phone for people in Canada.",
        "category": "mental-health",
        "imageUrl": "https://images.unsplash.com/photo-1493836512294-502baa1986e2",
        "location": "Canada-wide",
        "tags": ["crisis", "mental-health", "phone"],
        "urgent": True,
    },
    {
        "id": 5,
        "title": "YMCA Newcomer Settlement Services",
        "description": "Settlement workers who can help with forms, local services, job search, and referrals.",
        "category": "settlement-worker",
        "imageUrl": "https://images.unsplash.com/photo-1521737604893-d14cc237f11d",
        "location": "Toronto, ON",
        "tags": ["settlement", "newcomers", "forms"],
        "urgent": False,
    },
    {
        "id": 6,
        "title": "Newcomer Community Welcome Group",
        "description": "Local peer support group for meeting other newcomers and finding community events.",
        "category": "community-support",
        "imageUrl": "https://images.unsplash.com/photo-1511632765486-a01980e01a18",
        "location": "Calgary, AB",
        "tags": ["community", "events", "peer-support"],
        "urgent": False,
    },
]

POSTS = [
    {
        "id": 1,
        "title": "Apply for your health card as soon as possible",
        "description": "Some provinces have waiting periods, so early application can help reduce coverage gaps.",
        "category": "healthcare",
        "imageUrl": "https://images.unsplash.com/photo-1505751172876-fa1923c5c528",
        "location": "Canada-wide",
        "tags": ["recommended", "health-card", "new-arrivals"],
        "urgent": False,
    },
    {
        "id": 2,
        "title": "Know the warning signs of rental scams",
        "description": "Be careful with listings that ask for money before viewings or avoid written agreements.",
        "category": "housing",
        "imageUrl": "https://images.unsplash.com/photo-1560518883-ce09059eeffa",
        "location": "Canada-wide",
        "tags": ["recommended", "renting", "scam-prevention"],
        "urgent": False,
    },
    {
        "id": 3,
        "title": "Call 911 for immediate danger",
        "description": "If there is an immediate threat to life or safety, call emergency services right away.",
        "category": "legal-rights",
        "imageUrl": "https://images.unsplash.com/photo-1584433144859-1fc3ab64a957",
        "location": "Canada-wide",
        "tags": ["emergency", "safety", "urgent"],
        "urgent": True,
    },
    {
        "id": 4,
        "title": "Free mental health support is available",
        "description": "Newcomer stress is common, and confidential support is available through crisis lines and community agencies.",
        "category": "mental-health",
        "imageUrl": "https://images.unsplash.com/photo-1493836512294-502baa1986e2",
        "location": "Canada-wide",
        "tags": ["recommended", "mental-health", "support"],
        "urgent": False,
    },
    {
        "id": 5,
        "title": "Settlement workers can help you navigate first steps",
        "description": "Settlement agencies can help with health cards, SIN applications, language classes, and local referrals.",
        "category": "settlement-worker",
        "imageUrl": "https://images.unsplash.com/photo-1521737604893-d14cc237f11d",
        "location": "Canada-wide",
        "tags": ["recommended", "settlement", "documents"],
        "urgent": False,
    },
    {
        "id": 6,
        "title": "Join a community group in your city",
        "description": "Community groups can help newcomers build friendships, ask questions, and find local services.",
        "category": "community-support",
        "imageUrl": "https://images.unsplash.com/photo-1511632765486-a01980e01a18",
        "location": "Canada-wide",
        "tags": ["community", "events", "support"],
        "urgent": False,
    },
]
